"""empty message

Revision ID: c49bfe94e412
Revises: None
Create Date: 2016-11-17 15:23:43.948200

"""

# revision identifiers, used by Alembic.
revision = 'c49bfe94e412'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('fb_id', sa.String(length=128), nullable=True),
    sa.Column('created_time', sa.String(length=128), nullable=True),
    sa.Column('ad_id', sa.String(length=128), nullable=True),
    sa.Column('ad_name', sa.String(length=128), nullable=True),
    sa.Column('adset_id', sa.String(length=128), nullable=True),
    sa.Column('adset_name', sa.String(length=128), nullable=True),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_name', sa.String(length=128), nullable=True),
    sa.Column('form_id', sa.String(length=128), nullable=True),
    sa.Column('is_organic', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('street_address', sa.String(length=128), nullable=True),
    sa.Column('zip_code', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facebook_lead')
    ### end Alembic commands ###
